### ISSUE TITLE
Dynamic collection names?

### ISSUE THREAD

**Issue by simme** [danthorpe/Examples#8] opened 2016-04-09 20:40 UTC
Hey,

First off, thank you for a great project. :)

Second. I'm wondering if it would be possible (without going through too many hoops) to make the collection property dynamic. For example, say you have one collection called `categories` where each `Category` contains `Item`s. It would then be neat to make `Item`s of a specific `Category` be stored in a collection based on the key of that `Category`.

So items in the `Category` with an identifier of `foobar` could have their collection identifier be `foobar-items` for example. This would make fetching all items in one category trivial. And it seems to align pretty well with how key/value stores often are used!

**Comment by danthorpe** [comment] 2016-04-14 21:30
Hi @simme - sorry - I've only just seen this issue - must have got lost in the mails.

First off - I think it would make sense to move this to either TaylorSource or YapDatabaseExtensions instead of this repo. I'm assuming you're talking about the `Persistable` protocol in YapDatabaseExtensions?

In which case - the issue is that it's a static property so this sort of thing is exactly the trade-off that the project makes.

What you want is fairly trivial to do though with the Relationship extension in YapDatabase itself. Essentially your `Category` & `Item` example is a one-to-many relationship, and doing things like getting all the items in a particular category is really easy.

``` swift
extension Item {
    static let categoryRelationshipName = "category<-item" // this is the back reference
}

// Assuming that Item is a value type (see ValueCoding project)
extension ItemArchiver: YapDatabaseRelationshipNode {

    public func yapDatabaseRelationshipEdges() -> [AnyObject]! {
        var edges = Array<YapDatabaseRelationshipEdge>()

        // This registers the back reference from Item to Category
        // It assumes that you store the `YapDB.Index` to the category inside the Item
        // somehow. You could make do with just the key to the category though
        if let categorytID = value.cateborytID {
            let edge = YapDatabaseRelationshipEdge(
                name: Item.categoryRelationshipName,
                sourceKey: value.identifier,
                collection: Item.collection,
                destinationKey: categoryID.key,
                collection: categoryID.collection,
                nodeDeleteRules: YDB_NodeDeleteRules.DeleteSourceIfDestinationDeleted)
            edges.append(edge)
        }

        return edges
    }
}

extension Category {

    func itemsWithTransaction(transaction: ReadTransactionType) -> [Item] {
        var items = [Item]()
        if let relationship = transaction.ext("relationships") as? YapDatabaseRelationshipTransaction {
            relationship.enumerateEdgesWithName(Item. categoryRelationshipName, destinationKey: identifier, collection: Category.collection) { edge, stop in
                if let item: Item = transaction.read(edge.sourceKey) {
                    items.append(reminder)
                }
            }
        }
        return items
    }
}
```

Given something like the above, you can then do stuff like this:

``` swift
let categoryKey = "foobar"
let connection = database.newConnection()
let itemsInCategory = connection.read { transaction in
    let category: Category = transaction.readByKey(categoryKey)
    return category.itemsWithTransaction(transaction)
}
```

What this is essentially doing is the following:
1. Get the category you want.
2. From the category, using the relationship extension (read the YapDatabase docs on how to use this more), find all the Items which have this category (i.e. `self`) as a back reference.
3. That's it.

**Comment by simme** [comment] 2016-04-15 07:18
My bad, this was totally supposed to be in the `YapDatabaseExtensions` repo!

Thank you very much for the write up! Really appreciated :)

**Comment by danthorpe** [comment] 2016-04-15 07:36
No worries - I'm gonna close this. Feel free to open more issues in YapDatabaseExtensions. 😀

**Closed as completed by danthorpe** 2016-04-15 07:36 UTC
